import {
  albumCubeConfig,
  footerConfig,
  heroConfig,
  parallaxGalleryConfig,
  tourScheduleConfig,
} from '../config';
import type { CmsPage, CmsSection } from './types';
import { PAGE_ORDER } from './types';

function sid(n: number): string {
  return `a0000000-0000-4000-8000-${n.toString(16).padStart(12, '0')}`;
}

export const DEFAULT_PAGES: CmsPage[] = PAGE_ORDER.map((p) => ({
  slug: p.slug,
  title: p.title,
  path: p.path,
}));

export const DEFAULT_SECTIONS: CmsSection[] = [
  {
    id: sid(1),
    page_slug: 'home',
    type: 'hero',
    label: 'Copertina',
    sort_order: 0,
    visible: true,
    layout: {},
    content: {
      backgroundImage: heroConfig.backgroundImage,
      brandName: heroConfig.brandName,
      decodeText: heroConfig.decodeText,
      decodeChars: heroConfig.decodeChars,
      subtitle: heroConfig.subtitle,
      ctaPrimary: heroConfig.ctaPrimary,
      ctaPrimaryTarget: heroConfig.ctaPrimaryTarget,
      ctaSecondary: heroConfig.ctaSecondary,
      ctaSecondaryTarget: heroConfig.ctaSecondaryTarget,
      cornerLabel: heroConfig.cornerLabel,
      cornerDetail: heroConfig.cornerDetail,
      navItems: heroConfig.navItems,
    },
  },
  {
    id: sid(2),
    page_slug: 'home',
    type: 'album_cube',
    label: 'Cubo prodotti',
    sort_order: 1,
    visible: true,
    layout: {},
    content: {
      scrollHint: albumCubeConfig.scrollHint,
      tapHint: albumCubeConfig.tapHint,
      albums: albumCubeConfig.albums,
      cubeTextures: albumCubeConfig.cubeTextures,
    },
  },
  {
    id: sid(3),
    page_slug: 'home',
    type: 'parallax_gallery',
    label: 'Galleria',
    sort_order: 2,
    visible: true,
    layout: {},
    content: {
      sectionLabel: parallaxGalleryConfig.sectionLabel,
      sectionTitle: parallaxGalleryConfig.sectionTitle,
      galleryLabel: parallaxGalleryConfig.galleryLabel,
      galleryTitle: parallaxGalleryConfig.galleryTitle,
      marqueeTexts: parallaxGalleryConfig.marqueeTexts,
      endCtaText: parallaxGalleryConfig.endCtaText,
      parallaxImagesTop: parallaxGalleryConfig.parallaxImagesTop,
      parallaxImagesBottom: parallaxGalleryConfig.parallaxImagesBottom,
      galleryImages: parallaxGalleryConfig.galleryImages,
    },
  },
  {
    id: sid(4),
    page_slug: 'home',
    type: 'tour_schedule',
    label: 'Assistenza in evidenza',
    sort_order: 3,
    visible: true,
    layout: {},
    content: {
      sectionLabel: tourScheduleConfig.sectionLabel,
      sectionTitle: tourScheduleConfig.sectionTitle,
      vinylImage: tourScheduleConfig.vinylImage,
      buyButtonText: tourScheduleConfig.buyButtonText,
      detailsButtonText: tourScheduleConfig.detailsButtonText,
      bottomNote: tourScheduleConfig.bottomNote,
      bottomCtaText: tourScheduleConfig.bottomCtaText,
      statusLabels: tourScheduleConfig.statusLabels,
      tourDates: tourScheduleConfig.tourDates,
    },
  },
  {
    id: sid(5),
    page_slug: 'home',
    type: 'footer',
    label: 'Piè di pagina',
    sort_order: 4,
    visible: true,
    layout: {},
    content: {
      portraitImage: footerConfig.portraitImage,
      portraitAlt: footerConfig.portraitAlt,
      heroTitle: footerConfig.heroTitle,
      heroSubtitle: footerConfig.heroSubtitle,
      artistLabel: footerConfig.artistLabel,
      artistName: footerConfig.artistName,
      artistSubtitle: footerConfig.artistSubtitle,
      brandName: footerConfig.brandName,
      brandDescription: footerConfig.brandDescription,
      quickLinksTitle: footerConfig.quickLinksTitle,
      quickLinks: footerConfig.quickLinks,
      contactTitle: footerConfig.contactTitle,
      emailLabel: footerConfig.emailLabel,
      email: footerConfig.email,
      phoneLabel: footerConfig.phoneLabel,
      phone: footerConfig.phone,
      addressLabel: footerConfig.addressLabel,
      address: footerConfig.address,
      newsletterTitle: footerConfig.newsletterTitle,
      newsletterDescription: footerConfig.newsletterDescription,
      newsletterButtonText: footerConfig.newsletterButtonText,
      copyrightText: footerConfig.copyrightText,
      bottomLinks: footerConfig.bottomLinks,
      socialLinks: footerConfig.socialLinks,
      galleryImages: footerConfig.galleryImages,
      isoLogo: '',
      isoHref: '',
    },
  },

  {
    id: sid(10),
    page_slug: 'games',
    type: 'intro',
    label: 'Introduzione',
    sort_order: 0,
    visible: true,
    layout: {},
    content: {
      text: 'Spazio Game offre schede di gioco comma 6a con payout al 65%, complete di cabinet e monitor. Le nostre schede includono multigame con 7 titoli diversi, hardware affidabile e supporto tecnico dedicato.',
    },
  },
  {
    id: sid(11),
    page_slug: 'games',
    type: 'split',
    label: 'Master 5',
    sort_order: 1,
    visible: true,
    layout: { imageSide: 'left', imageRatio: 'video', imageFit: 'contain' },
    content: {
      eyebrow: 'Scheda Comma 6a',
      title: 'Master 5',
      image: '/master5-game.jpg',
      imageAlt: 'Master 5 - Scheda di gioco',
      specs: [
        { label: 'Hardware', value: 'ASTX-R1' },
        { label: 'Payout', value: '65%' },
        { label: 'Schermo', value: 'Monitor 19" compatibile' },
      ],
      listTitle: 'Giochi Inclusi (7 titoli)',
      list: [
        'Clash for the Empire',
        'Farms Gold',
        'Fruit Bar',
        'Jungle Course',
        'Pendragon',
        'West Cowboy',
        'Wild Galleon',
      ],
      ctaText: 'Scarica Scheda Esplicativa',
      ctaHref: '#',
    },
  },
  {
    id: sid(12),
    page_slug: 'games',
    type: 'split',
    label: 'Super 7',
    sort_order: 2,
    visible: true,
    layout: { imageSide: 'right', imageRatio: 'video', imageFit: 'contain' },
    content: {
      eyebrow: 'Scheda Comma 6a',
      title: 'Super 7',
      image: '/super7-game.jpg',
      imageAlt: 'Super 7 - Scheda di gioco',
      specs: [
        { label: 'Hardware', value: 'G_640S' },
        { label: 'Payout', value: '65%' },
        { label: 'Schermo', value: 'Monitor 19" compatibile' },
      ],
      listTitle: 'Giochi Inclusi (5 titoli)',
      list: ["Pirate's Treasure", 'The Book of Egypt', 'Irish Gardens', 'Diamonds Fever', 'The Chicken'],
      ctaText: 'Scarica Scheda Esplicativa',
      ctaHref: '#',
    },
  },
  {
    id: sid(14),
    page_slug: 'games',
    type: 'provider_groups',
    label: 'Giochi per marchio',
    sort_order: 3,
    visible: true,
    layout: { columns: 4, imageFit: 'contain' },
    content: {
      title: 'Giochi per marchio',
      items: [
        {
          name: 'Octavian',
          logo: '/games-scheda.jpg',
          href: 'https://',
          games: [
            { title: 'Gioco 1', image: '/master5-game.jpg', href: '' },
            { title: 'Gioco 2', image: '/super7-game.jpg', href: '' },
            { title: 'Gioco 3', image: '/games-scheda.jpg', href: '' },
          ],
        },
        {
          name: 'Cristaltec',
          logo: '/games-scheda.jpg',
          href: 'https://',
          games: [
            { title: 'Gioco 1', image: '/games-scheda.jpg', href: '' },
            { title: 'Gioco 2', image: '/master5-game.jpg', href: '' },
          ],
        },
      ],
    },
  },
  {
    id: sid(13),
    page_slug: 'games',
    type: 'cta',
    label: 'Contatto',
    sort_order: 4,
    visible: true,
    layout: {},
    content: {
      title: 'Vuoi saperne di più?',
      text: 'Contattaci per ricevere informazioni dettagliate sulle nostre schede di gioco, i giochi disponibili e le condizioni commerciali.',
      buttonText: 'Richiedi Informazioni',
      buttonHref: 'mailto:info@spaziogame.net',
    },
  },

  {
    id: sid(20),
    page_slug: 'cabinet',
    type: 'intro',
    label: 'Introduzione',
    sort_order: 0,
    visible: true,
    layout: {},
    content: {
      text: 'Il cabinet Earth di Spazio Game è progettato per valorizzare qualsiasi sala da gioco. Pratico, facile da trasportare e compatibile con tutte le schede presenti sul mercato. Disponibile anche in versione blindata.',
    },
  },
  {
    id: sid(21),
    page_slug: 'cabinet',
    type: 'split',
    label: 'Cabinet Earth',
    sort_order: 1,
    visible: true,
    layout: { imageSide: 'left', imageRatio: 'portrait', imageFit: 'contain' },
    content: {
      title: 'Earth',
      subtitle: 'Cabinet Mobile',
      image: '/cabinet-earth.jpg',
      imageAlt: 'Cabinet Earth',
      badge: 'Disponibile versione blindata',
      blocks: [
        {
          type: 'text',
          title: 'Design',
          body: 'Il mobile "Earth" valorizza la propria sala da gioco, adatto a qualsiasi ambiente, pratico e facile da trasportare, compatibile con tutte le schede presenti sul mercato.',
        },
        {
          type: 'list',
          title: 'Dati Tecnici',
          items: [
            'Hopper cctalk: (Azkoyen - Alberici)',
            'Gettoniera cctalk: (Azkoyen - Alberici)',
            'Separatore cctalk: (Azkoyen - Alberici)',
            'Monitor 19"',
          ],
        },
        {
          type: 'list',
          title: 'Accessori',
          items: [
            'Hopper con carrello estraibile',
            'Testatina luminosa personalizzabile',
            'Porta documenti',
            'Porta minuterie',
          ],
        },
        {
          type: 'callout',
          title: 'Blindato',
          body: 'Disponibile in versione blindata per maggiore sicurezza.',
        },
      ],
    },
  },
  {
    id: sid(22),
    page_slug: 'cabinet',
    type: 'feature_grid',
    label: 'Caratteristiche',
    sort_order: 2,
    visible: true,
    layout: { columns: 3 },
    content: {
      title: 'Caratteristiche Principali',
      items: [
        {
          title: 'Compatibile',
          desc: 'Compatibile con tutte le schede presenti sul mercato, inclusi Master 5 e Super 7.',
        },
        {
          title: 'Trasportabile',
          desc: 'Design pratico e facile da trasportare, ideale per qualsiasi ambiente.',
        },
        {
          title: 'Personalizzabile',
          desc: 'Testatina luminosa personalizzabile per valorizzare la tua sala.',
        },
      ],
    },
  },
  {
    id: sid(23),
    page_slug: 'cabinet',
    type: 'cta',
    label: 'Contatto',
    sort_order: 3,
    visible: true,
    layout: {},
    content: {
      title: 'Valuta il tuo nuovo cabinet',
      text: 'Contattaci per scoprire le caratteristiche complete del cabinet Earth e ricevere un preventivo personalizzato per la tua sala.',
      buttonText: 'Richiedi Preventivo',
      buttonHref: 'mailto:info@spaziogame.net',
    },
  },

  {
    id: sid(30),
    page_slug: 'monitor',
    type: 'intro',
    label: 'Introduzione',
    sort_order: 0,
    visible: true,
    layout: {},
    content: {
      text: 'Spazio Game offre monitor open-frame da 17", 19" LCD e 19" LED in formato 4:3, progettati specificatamente per l\'installazione in cabinet da gioco. Monitor affidabili, luminosi e compatibili con tutte le schede comma 6a.',
    },
  },
  {
    id: sid(31),
    page_slug: 'monitor',
    type: 'split_list',
    label: 'Modelli monitor',
    sort_order: 1,
    visible: true,
    layout: { imageFit: 'contain' },
    content: {
      items: [
        {
          title: '17"',
          eyebrow: 'LCD',
          subtitle: 'Rapporto 4:3',
          body: 'Monitor LCD 17 pollici con rapporto 4:3, ideale per installazioni compatte.',
          image: '/monitor-open.jpg',
          imageAlt: 'Monitor 17 LCD',
          listTitle: 'Caratteristiche',
          list: [
            'Risoluzione ottimale per giochi comma 6a',
            'Compatibile con tutte le schede',
            'Durata elevata',
            'Consumo ridotto',
          ],
        },
        {
          title: '19"',
          eyebrow: 'LCD',
          subtitle: 'Rapporto 4:3',
          body: 'Monitor LCD 19 pollici con rapporto 4:3, standard del settore per sale giochi.',
          image: '/monitor-open.jpg',
          imageAlt: 'Monitor 19 LCD',
          listTitle: 'Caratteristiche',
          list: [
            'Display luminoso e nitido',
            'Angolo di visione ampio',
            'Montaggio semplificato',
            'Progettato per uso continuativo',
          ],
        },
        {
          title: '19"',
          eyebrow: 'LED',
          subtitle: 'Rapporto 4:3',
          body: 'Monitor LED 19 pollici con retroilluminazione LED, massima luminosità e risparmio energetico.',
          image: '/monitor-open.jpg',
          imageAlt: 'Monitor 19 LED',
          listTitle: 'Caratteristiche',
          list: [
            'Retroilluminazione LED',
            'Consumo energetico ridotto',
            'Colori brillanti e saturi',
            'Durata superiore ai LCD tradizionali',
          ],
        },
      ],
    },
  },
  {
    id: sid(32),
    page_slug: 'monitor',
    type: 'table',
    label: 'Confronto modelli',
    sort_order: 2,
    visible: true,
    layout: {},
    content: {
      title: 'Confronto Modelli',
      headers: ['Modello', 'Dimensione', 'Tipo', 'Rapporto', 'Ideale per'],
      rows: [
        ['LCD 17"', '17 pollici', 'LCD', '4:3', 'Installazioni compatte'],
        ['LCD 19"', '19 pollici', 'LCD', '4:3', 'Standard sala giochi'],
        ['LED 19"', '19 pollici', 'LED', '4:3', 'Massima luminosità'],
      ],
    },
  },
  {
    id: sid(33),
    page_slug: 'monitor',
    type: 'cta',
    label: 'Contatto',
    sort_order: 3,
    visible: true,
    layout: {},
    content: {
      title: 'Scegli il monitor perfetto',
      text: 'Contattaci per ricevere informazioni dettagliate sui nostri monitor open-frame e trovare la soluzione ideale per i tuoi cabinet.',
      buttonText: 'Richiedi Informazioni',
      buttonHref: 'mailto:info@spaziogame.net',
    },
  },

  {
    id: sid(40),
    page_slug: 'accessori',
    type: 'intro',
    label: 'Introduzione',
    sort_order: 0,
    visible: true,
    layout: {},
    content: {
      text: 'Completiamo la tua sala giochi con una gamma completa di accessori: divisori, sgabelli, cambia-cambia e separè. Ogni accessorio è selezionato per garantire qualità, durata e un design che valorizza il tuo spazio.',
    },
  },
  {
    id: sid(41),
    page_slug: 'accessori',
    type: 'feature_grid',
    label: 'Categorie',
    sort_order: 1,
    visible: true,
    layout: { columns: 2 },
    content: {
      title: '',
      items: [
        {
          title: 'Divisori',
          desc: 'Divisori professionali per organizzare gli spazi di gioco. Design moderno e robustezza per un uso intensivo.',
          features: [
            'Separazione ottimale tra postazioni',
            'Materiali di alta qualità',
            'Design personalizzabile',
            'Installazione semplice',
          ],
        },
        {
          title: 'Sgabelli',
          desc: 'Sgabelli ergonomici progettati per il comfort dei giocatori durante le sessioni di gioco.',
          features: [
            'Seduta ergonomica e confortevole',
            'Regolazione in altezza',
            'Base stabile e resistente',
            'Rivestimento in eco-pelle',
          ],
        },
        {
          title: 'Cambia Cambia',
          desc: 'Dispositivo per la gestione dei cambi automatico, indispensabile per le sale giochi professionali.',
          features: [
            'Gestione automatica cambi',
            'Compatibile con tutti i sistemi',
            'Velocità di erogazione rapida',
            'Manutenzione semplificata',
          ],
        },
        {
          title: 'Separè',
          desc: 'Elementi divisori con illuminazione LED per creare ambienti accoglienti e moderni.',
          features: [
            'Illuminazione LED integrata',
            'Design moderno ed elegante',
            'Vari colori disponibili',
            'Facile da posizionare',
          ],
        },
      ],
    },
  },
  {
    id: sid(42),
    page_slug: 'accessori',
    type: 'image_cards',
    label: 'Prodotti',
    sort_order: 2,
    visible: true,
    layout: { columns: 3, imageFit: 'contain' },
    content: {
      title: 'I Nostri Prodotti',
      items: [
        {
          image: '/sgabelli.jpg',
          title: 'Sgabelli Gaming',
          desc: 'Ergonomici e resistenti, ideali per sessioni di gioco prolungate.',
        },
        {
          image: '/accessori-divisori.jpg',
          title: 'Divisori',
          desc: 'Per organizzare gli spazi e creare zone di gioco separate.',
        },
        {
          image: '/separatore.jpg',
          title: 'Separè LED',
          desc: 'Divisori illuminati per ambienti moderni ed eleganti.',
        },
      ],
    },
  },
  {
    id: sid(43),
    page_slug: 'accessori',
    type: 'brands',
    label: 'Marchi',
    sort_order: 3,
    visible: true,
    layout: {},
    content: {
      title: 'Marchi Disponibili',
      text: 'Lavoriamo con i migliori marchi del settore per garantire qualità e affidabilità.',
      items: ['Alberici', 'Baldazzi', 'Azkoyen'],
    },
  },
  {
    id: sid(44),
    page_slug: 'accessori',
    type: 'cta',
    label: 'Contatto',
    sort_order: 4,
    visible: true,
    layout: {},
    content: {
      title: 'Completa la tua sala',
      text: 'Scopri tutti gli accessori disponibili e crea la sala giochi perfetta. Contattaci per un preventivo personalizzato.',
      buttonText: 'Richiedi Preventivo',
      buttonHref: 'mailto:info@spaziogame.net',
    },
  },

  {
    id: sid(50),
    page_slug: 'assistenza',
    type: 'intro',
    label: 'Introduzione',
    sort_order: 0,
    visible: true,
    layout: {},
    content: {
      text: 'Il nostro centro assistenza offre supporto professionale per noleggiatori e concessionari. Riparazione schede, fornitura ricambi, assistenza tecnica e consulenza hardware: un servizio completo per garantire il massimo uptime delle tue macchine.',
    },
  },
  {
    id: sid(51),
    page_slug: 'assistenza',
    type: 'split_list',
    label: 'Servizi',
    sort_order: 1,
    visible: true,
    layout: { imageFit: 'contain' },
    content: {
      items: [
        {
          title: 'Riparazione Schede',
          eyebrow: 'SCHEDE',
          body: 'Riparazione e manutenzione di schede e apparecchi da intrattenimento. Interventi rapidi e professionali per minimizzare i tempi di fermo macchina.',
          image: '/assistenza-tech.jpg',
          imageAlt: 'Riparazione schede',
          list: [
            'Diagnosi tecnica avanzata',
            'Riparazione componenti elettronici',
            'Sostituzione parti danneggiate',
            'Test funzionale completo',
          ],
        },
        {
          title: 'Ricambi e Periferiche',
          eyebrow: 'RICAMBI',
          body: 'Fornitura di monitor, pulsanti, hopper, lettori di banconote, schede CPU e tutti i ricambi originali per il tuo parco macchine.',
          image: '/assistenza-tech.jpg',
          imageAlt: 'Ricambi',
          list: ['Monitor LCD e LED', 'Pulsanti e comandi', 'Hopper e gettoniere', 'Lettori di banconote', 'Schede CPU'],
        },
        {
          title: 'Supporto Tecnico',
          eyebrow: 'SUPPORTO',
          body: 'Supporto tecnico personalizzato per esigenze specifiche dei noleggiatori. Consulenza dedicata per risolvere ogni problematica.',
          image: '/assistenza-tech.jpg',
          imageAlt: 'Supporto tecnico',
          list: ['Assistenza telefonica', 'Intervento in loco', 'Manutenzione programmata', 'Formazione operatore'],
        },
        {
          title: 'Consulenza Hardware',
          eyebrow: 'CONSULENZA',
          body: 'Consulenza sulla compatibilità e aggiornamenti hardware. Ti aiutiamo a scegliere le soluzioni migliori per il tuo parco macchine.',
          image: '/assistenza-tech.jpg',
          imageAlt: 'Consulenza hardware',
          list: [
            'Analisi parco macchine',
            'Consigli aggiornamento',
            'Verifica compatibilità',
            'Pianificazione investimenti',
          ],
        },
      ],
    },
  },
  {
    id: sid(52),
    page_slug: 'assistenza',
    type: 'feature_grid',
    label: 'Perché noi',
    sort_order: 2,
    visible: true,
    layout: { columns: 3 },
    content: {
      title: 'Perché Scegliere la Nostra Assistenza',
      items: [
        {
          title: 'Interventi Rapidi',
          desc: 'Tempi di intervento ridotti al minimo per garantire la continuità del tuo business.',
        },
        {
          title: 'Tecnici Qualificati',
          desc: 'Team di tecnici specializzati con anni di esperienza nel settore del gaming.',
        },
        {
          title: 'Supporto Diretto',
          desc: 'Linea diretta con il nostro centro assistenza per ogni esigenza.',
        },
      ],
    },
  },
  {
    id: sid(53),
    page_slug: 'assistenza',
    type: 'contact_banner',
    label: 'Banner contatto',
    sort_order: 3,
    visible: true,
    layout: {},
    content: {
      title: 'Centro Assistenza SpazioGame',
      text: 'Tel: +39 0374 871615 | Email: info@spaziogame.net',
      buttonText: 'Chiama Ora',
      buttonHref: 'tel:+390374871615',
    },
  },
  {
    id: sid(54),
    page_slug: 'assistenza',
    type: 'cta',
    label: 'Contatto',
    sort_order: 4,
    visible: true,
    layout: {},
    content: {
      title: 'Serve assistenza?',
      text: 'Contattaci subito per ricevere supporto tecnico professionale. Siamo a tua disposizione per ogni esigenza.',
      buttonText: 'Chiama Ora',
      buttonHref: 'tel:+390374871615',
      button2Text: 'Scrivici',
      button2Href: 'mailto:info@spaziogame.net',
    },
  },
];
